language: perl
perl:
  - 5.1
  - "5.2"

install:
  # - cpanm --quiet --installdeps
  - cpanm --quiet --installdeps Cookie::Baker

before_script:
  -

env:
  - E1: RED
  - E2: BLUE

#
script:
  - perl ./test_it.pl arg1 arg2
